before:
  hooks:
builds:
- env:
  - CGO_ENABLED=0
  goos:
    - linux
    - darwin
    - windows
    - netbsd
    - openbsd
    - freebsd
  goarch:
    - 386
    - amd64
    - arm
    - arm64
archive:
  name_template: '{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ if .Arm}}v{{ .Arm }}{{ end }}'
  replacements:
  format_overrides:
    - goos: windows
      format: zip
checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
