language: go

go:
  - 1.6
  - 1.7
  - 1.8
  - 1.9
  - master

install:
  - wget https://github.com/golang/dep/releases/download/v0.4.1/dep-linux-amd64 -O /tmp/dep
  - export PATH=$PATH:/tmp/dep
  - dep ensure

script:
  - sh test.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)