language: go

go:
  - 1.11.x

install: true

before_script:
  - wget https://github.com/golang/dep/releases/download/v0.5.0/dep-linux-amd64 -O /tmp/dep
  - chmod +x /tmp/dep
  - /tmp/dep ensure
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s v1.12.5

jobs:
  include:
    - stage: "Code Quality"
      name: "Code Quality Analysis"
      script: golangci-lint run
    - stage: "Tests"
      name: "Unit Tests"
      script: sh test.sh
      after_success:
        - bash <(curl -s https://codecov.io/bash)
    - stage: "Release"
      name: "Release Binaries"
      script: skip
      deploy:
        - provider: script
          skip_cleanup: true
          script: curl -sL https://git.io/goreleaser | bash
          on:
            tags: true
            condition: $TRAVIS_OS_NAME = linux