language: go

go:
  - 1.6
  - 1.7
  - 1.8
  - 1.9
  - 1.10
  - master

install:
  - go get -v github.com/Masterminds/glide
  - cd $GOPATH/src/github.com/Masterminds/glide && git checkout 84607742b10f492430762d038e954236bbaf23f7 && go install && cd -
  - glide install

script:
  - sh test.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)