language: go

go:
  - 1.6
  - 1.7
  - 1.8
  - master

install:
  - go get -v github.com/Masterminds/glide
  - cd $GOPATH/src/github.com/Masterminds/glide && git checkout 84607742b10f492430762d038e954236bbaf23f7 && go install && cd -
  - glide install

script: go test $(go list ./... | grep -v /vendor/) -v