[[constraint]]
  name = "github.com/spf13/cobra"
  version = "=0.0.3"

[[constraint]]
  name = "github.com/mvdan/xurls"
  version = "=v2.0.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "=v1.3.0"

[prune]
  go-tests = true
  unused-packages = true
